name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          cp hetzner-debian-installer.bash /tmp/hetzner-debian-installer.bash
          chmod +x /tmp/hetzner-debian-installer.bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/hetzner-debian-installer.bash
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

